In [ ]:
import pandas as pd

# Direct download link for the CSV file
csv_url = "https://drive.google.com/uc?id=176NNytWYrrHNoe1ogaxRPwYm3nnyqGWp"

# Read the CSV file into a DataFrame
df = pd.read_csv(csv_url)

# Display the DataFrame
print(df)

                                                  Model  Price  Age     KM  \
0         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500   23  46986
1         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750   23  72937
2         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950   24  41711
3         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950   26  48000
4           TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750   30  38500
...                                                 ...    ...  ...    ...
1431         TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors   7500   69  20544
1432  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...  10845   72  19000
1433  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8500   71  17016
1434  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7250   70  16916
1435        TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors   6950   76      1

     Fuel_Type   HP  Met_Color  Automatic    cc  Doors  Weight part
0       Diesel   90          1          0  2000      3    1165    V
1       Diesel   90          1          0  2000      3    1165    S
2       Diesel   90          1          0  2000      3    1165    V
3       Diesel   90          0          0  2000      3    1165    V
4       Diesel   90          0          0  2000      3    1170    S
...        ...  ...        ...        ...   ...    ...     ...  ...
1431    Petrol   86          1          0  1300      3    1025    V
1432    Petrol   86          0          0  1300      3    1015    S
1433    Petrol   86          0          0  1300      3    1015    S
1434    Petrol   86          1          0  1300      3    1015    S
1435    Petrol  110          0          0  1600      5    1114    S

[1436 rows x 12 columns]

In [ ]:
df

,Model,Price,Age,KM,Fuel_Type,HP,Met_Color,Automatic,cc,Doors,Weight,part
0,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,46986,Diesel,90,1,0,2000,3,1165,V
1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,72937,Diesel,90,1,0,2000,3,1165,S
2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,41711,Diesel,90,1,0,2000,3,1165,V
3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,48000,Diesel,90,0,0,2000,3,1165,V
4,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,38500,Diesel,90,0,0,2000,3,1170,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1431,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,20544,Petrol,86,1,0,1300,3,1025,V
1432,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,19000,Petrol,86,0,0,1300,3,1015,S
1433,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,17016,Petrol,86,0,0,1300,3,1015,S
1434,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,16916,Petrol,86,1,0,1300,3,1015,S
1435,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,1,Petrol,110,0,0,1600,5,1114,S

In [ ]:
sample_df = df.sample(n = 600, random_state=123)

In [ ]:
sample_df

,Model,Price,Age,KM,Fuel_Type,HP,Met_Color,Automatic,cc,Doors,Weight,part
585,TOYOTA Corolla 1.6 16V VVT I HATCHB SOL AUT4 2...,12950,50,29686,Petrol,110,1,1,1600,3,1075,V
61,TOYOTA Corolla 1.6 16V VVT I 5DR SOL 4/5-Doors,16500,27,37177,Petrol,110,0,0,1600,5,1130,S
919,TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors,9900,62,57179,Petrol,110,1,0,1600,5,1075,V
624,TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors,7950,67,135337,CNG,110,1,0,1600,5,1120,V
36,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15950,25,25000,Petrol,97,0,0,1400,3,1100,S
...,...,...,...,...,...,...,...,...,...,...,...,...
598,TOYOTA Corolla 1.4 16V VVT I HATCHB TERRA 2/3-...,10450,48,15000,Petrol,97,1,0,1400,3,1025,V
642,TOYOTA Corolla 1.6 16V SEDAN LINEA TERRA 4/5-D...,7950,68,119289,Petrol,110,1,0,1600,4,1035,S
52,TOYOTA Corolla 1.6 16V VVT I 5DR SOL AUT4 4/5-...,20500,26,56000,Petrol,110,1,1,1600,5,1180,V
151,TOYOTA Corolla 1.6 16V VVT I 5DR SOL BNS 4/5-D...,19950,19,17038,Petrol,110,0,0,1600,5,1130,S
41,TOYOTA Corolla 1.4 16V VVT I 3DR 2/3-Doors,16750,27,44068,Petrol,97,1,0,1400,3,1100,V

In [ ]:

# Identify missing values
missing_values = sample_df.isnull().sum()
print(missing_values)

Model        0
Price        0
Age          0
KM           0
Fuel_Type    0
HP           0
Met_Color    0
Automatic    0
cc           0
Doors        0
Weight       0
part         0
dtype: int64

In [ ]:
sample_df.dropna(inplace=True)

In [ ]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 600 entries, 585 to 41
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Model      600 non-null    object
 1   Price      600 non-null    int64
 2   Age        600 non-null    int64
 3   KM         600 non-null    int64
 4   Fuel_Type  600 non-null    object
 5   HP         600 non-null    int64
 6   Met_Color  600 non-null    int64
 7   Automatic  600 non-null    int64
 8   cc         600 non-null    int64
 9   Doors      600 non-null    int64
 10  Weight     600 non-null    int64
 11  part       600 non-null    object
dtypes: int64(9), object(3)
memory usage: 60.9+ KB

In [ ]:
df_encoded = pd.get_dummies(sample_df, columns=['Fuel_Type','part'])
df_encoded

,Model,Price,Age,KM,HP,Met_Color,Automatic,cc,Doors,Weight,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,part_S,part_V
585,TOYOTA Corolla 1.6 16V VVT I HATCHB SOL AUT4 2...,12950,50,29686,110,1,1,1600,3,1075,False,False,True,False,True
61,TOYOTA Corolla 1.6 16V VVT I 5DR SOL 4/5-Doors,16500,27,37177,110,0,0,1600,5,1130,False,False,True,True,False
919,TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors,9900,62,57179,110,1,0,1600,5,1075,False,False,True,False,True
624,TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors,7950,67,135337,110,1,0,1600,5,1120,True,False,False,False,True
36,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,15950,25,25000,97,0,0,1400,3,1100,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,TOYOTA Corolla 1.4 16V VVT I HATCHB TERRA 2/3-...,10450,48,15000,97,1,0,1400,3,1025,False,False,True,False,True
642,TOYOTA Corolla 1.6 16V SEDAN LINEA TERRA 4/5-D...,7950,68,119289,110,1,0,1600,4,1035,False,False,True,True,False
52,TOYOTA Corolla 1.6 16V VVT I 5DR SOL AUT4 4/5-...,20500,26,56000,110,1,1,1600,5,1180,False,False,True,False,True
151,TOYOTA Corolla 1.6 16V VVT I 5DR SOL BNS 4/5-D...,19950,19,17038,110,0,0,1600,5,1130,False,False,True,True,False
41,TOYOTA Corolla 1.4 16V VVT I 3DR 2/3-Doors,16750,27,44068,97,1,0,1400,3,1100,False,False,True,False,True

In [ ]:
x = df_encoded.drop(columns=['Price'])
y = df_encoded['Price']
x

,Model,Age,KM,HP,Met_Color,Automatic,cc,Doors,Weight,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,part_S,part_V
585,TOYOTA Corolla 1.6 16V VVT I HATCHB SOL AUT4 2...,50,29686,110,1,1,1600,3,1075,False,False,True,False,True
61,TOYOTA Corolla 1.6 16V VVT I 5DR SOL 4/5-Doors,27,37177,110,0,0,1600,5,1130,False,False,True,True,False
919,TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors,62,57179,110,1,0,1600,5,1075,False,False,True,False,True
624,TOYOTA Corolla 1.6 16V LIFTB LINEA LUNA 4/5-Doors,67,135337,110,1,0,1600,5,1120,True,False,False,False,True
36,TOYOTA Corolla 1.4 16V VVT I 3DR TERRA COMFORT...,25,25000,97,0,0,1400,3,1100,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,TOYOTA Corolla 1.4 16V VVT I HATCHB TERRA 2/3-...,48,15000,97,1,0,1400,3,1025,False,False,True,False,True
642,TOYOTA Corolla 1.6 16V SEDAN LINEA TERRA 4/5-D...,68,119289,110,1,0,1600,4,1035,False,False,True,True,False
52,TOYOTA Corolla 1.6 16V VVT I 5DR SOL AUT4 4/5-...,26,56000,110,1,1,1600,5,1180,False,False,True,False,True
151,TOYOTA Corolla 1.6 16V VVT I 5DR SOL BNS 4/5-D...,19,17038,110,0,0,1600,5,1130,False,False,True,True,False
41,TOYOTA Corolla 1.4 16V VVT I 3DR 2/3-Doors,27,44068,97,1,0,1400,3,1100,False,False,True,False,True

In [ ]:
y

585    12950
61     16500
919     9900
624     7950
36     15950
       ...
598    10450
642     7950
52     20500
151    19950
41     16750
Name: Price, Length: 600, dtype: int64